create table "public"."assetBeneficiaries" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "name" text not null,
    "allocation" smallint not null,
    "alreadyAssigned" boolean not null
);


alter table "public"."assetBeneficiaries" enable row level security;

create table "public"."assets" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "name" text not null,
    "initialValue" bigint not null,
    "currentValue" bigint not null,
    "yearAcquired" integer not null,
    "rate" smallint not null,
    "term" smallint not null,
    "type" text not null,
    "taxable" boolean not null,
    "liquid" boolean not null,
    "toBeSold" boolean not null
);


alter table "public"."assets" enable row level security;

CREATE UNIQUE INDEX "assetBeneficiaries_pkey" ON public."assetBeneficiaries" USING btree (id);

CREATE UNIQUE INDEX assets_pkey ON public.assets USING btree (id);

alter table "public"."assetBeneficiaries" add constraint "assetBeneficiaries_pkey" PRIMARY KEY using index "assetBeneficiaries_pkey";

alter table "public"."assets" add constraint "assets_pkey" PRIMARY KEY using index "assets_pkey";

grant delete on table "public"."assetBeneficiaries" to "anon";

grant insert on table "public"."assetBeneficiaries" to "anon";

grant references on table "public"."assetBeneficiaries" to "anon";

grant select on table "public"."assetBeneficiaries" to "anon";

grant trigger on table "public"."assetBeneficiaries" to "anon";

grant truncate on table "public"."assetBeneficiaries" to "anon";

grant update on table "public"."assetBeneficiaries" to "anon";

grant delete on table "public"."assetBeneficiaries" to "authenticated";

grant insert on table "public"."assetBeneficiaries" to "authenticated";

grant references on table "public"."assetBeneficiaries" to "authenticated";

grant select on table "public"."assetBeneficiaries" to "authenticated";

grant trigger on table "public"."assetBeneficiaries" to "authenticated";

grant truncate on table "public"."assetBeneficiaries" to "authenticated";

grant update on table "public"."assetBeneficiaries" to "authenticated";

grant delete on table "public"."assetBeneficiaries" to "service_role";

grant insert on table "public"."assetBeneficiaries" to "service_role";

grant references on table "public"."assetBeneficiaries" to "service_role";

grant select on table "public"."assetBeneficiaries" to "service_role";

grant trigger on table "public"."assetBeneficiaries" to "service_role";

grant truncate on table "public"."assetBeneficiaries" to "service_role";

grant update on table "public"."assetBeneficiaries" to "service_role";

grant delete on table "public"."assets" to "anon";

grant insert on table "public"."assets" to "anon";

grant references on table "public"."assets" to "anon";

grant select on table "public"."assets" to "anon";

grant trigger on table "public"."assets" to "anon";

grant truncate on table "public"."assets" to "anon";

grant update on table "public"."assets" to "anon";

grant delete on table "public"."assets" to "authenticated";

grant insert on table "public"."assets" to "authenticated";

grant references on table "public"."assets" to "authenticated";

grant select on table "public"."assets" to "authenticated";

grant trigger on table "public"."assets" to "authenticated";

grant truncate on table "public"."assets" to "authenticated";

grant update on table "public"."assets" to "authenticated";

grant delete on table "public"."assets" to "service_role";

grant insert on table "public"."assets" to "service_role";

grant references on table "public"."assets" to "service_role";

grant select on table "public"."assets" to "service_role";

grant trigger on table "public"."assets" to "service_role";

grant truncate on table "public"."assets" to "service_role";

grant update on table "public"."assets" to "service_role";


