create type "public"."assetTypes" as enum ('Cash', 'Stocks', 'Bonds', 'Real Estate', 'Mutual Funds', 'Retirement Account', 'Crypto', 'Life Insurance');

create type "public"."provinces" as enum ('AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'NT', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT');

create table "public"."asset_beneficiaries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "allocation" smallint not null,
    "asset_id" bigint not null,
    "beneficary_id" bigint not null
);


alter table "public"."asset_beneficiaries" enable row level security;

create table "public"."assets" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "initial_value" numeric not null,
    "current_value" numeric not null,
    "year_acquired" integer not null,
    "rate" smallint not null,
    "term" smallint not null,
    "type" "assetTypes" not null,
    "taxable" boolean not null,
    "liquid" boolean not null,
    "to_be_sold" boolean not null
);


alter table "public"."assets" enable row level security;

create table "public"."beneficiaries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "allocation" smallint not null
);


alter table "public"."beneficiaries" enable row level security;

create table "public"."businesses" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "valuation" numeric not null,
    "ebitda" numeric not null,
    "appreciation_rate" smallint not null,
    "term" smallint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."businesses" enable row level security;

create table "public"."clients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "birth_date" date not null,
    "expected_retirement_age" smallint not null,
    "province" provinces not null,
    "annual_income" numeric not null,
    "income_mutiplier" smallint not null
);


alter table "public"."clients" enable row level security;

create table "public"."debts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "initial_value" numeric not null,
    "year_acquired" integer not null,
    "rate" smallint not null,
    "term" smallint not null,
    "annual_payment" numeric not null,
    "insurable_future_value_dollars" numeric not null
);


alter table "public"."debts" enable row level security;

create table "public"."goals" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "amount" numeric not null,
    "philanthropic" boolean not null
);


alter table "public"."goals" enable row level security;

create table "public"."shareholders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "share_percentage" smallint not null,
    "insurance_coverage" numeric not null,
    "ebitda_contribution_percentage" smallint not null,
    "business_id" bigint not null
);


alter table "public"."shareholders" enable row level security;

CREATE UNIQUE INDEX "assetBeneficiaries_pkey" ON public.asset_beneficiaries USING btree (id);

CREATE UNIQUE INDEX assets_pkey ON public.assets USING btree (id);

CREATE UNIQUE INDEX beneficiaries_pkey ON public.beneficiaries USING btree (id);

CREATE UNIQUE INDEX businesses_pkey ON public.businesses USING btree (id);

CREATE UNIQUE INDEX client_pkey ON public.clients USING btree (id);

CREATE UNIQUE INDEX debts_pkey ON public.debts USING btree (id);

CREATE UNIQUE INDEX goals_pkey ON public.goals USING btree (id);

CREATE UNIQUE INDEX shareholders_pkey ON public.shareholders USING btree (id);

alter table "public"."asset_beneficiaries" add constraint "assetBeneficiaries_pkey" PRIMARY KEY using index "assetBeneficiaries_pkey";

alter table "public"."assets" add constraint "assets_pkey" PRIMARY KEY using index "assets_pkey";

alter table "public"."beneficiaries" add constraint "beneficiaries_pkey" PRIMARY KEY using index "beneficiaries_pkey";

alter table "public"."businesses" add constraint "businesses_pkey" PRIMARY KEY using index "businesses_pkey";

alter table "public"."clients" add constraint "client_pkey" PRIMARY KEY using index "client_pkey";

alter table "public"."debts" add constraint "debts_pkey" PRIMARY KEY using index "debts_pkey";

alter table "public"."goals" add constraint "goals_pkey" PRIMARY KEY using index "goals_pkey";

alter table "public"."shareholders" add constraint "shareholders_pkey" PRIMARY KEY using index "shareholders_pkey";

alter table "public"."asset_beneficiaries" add constraint "public_assetBeneficiaries_assetId_fkey" FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE not valid;

alter table "public"."asset_beneficiaries" validate constraint "public_assetBeneficiaries_assetId_fkey";

alter table "public"."asset_beneficiaries" add constraint "public_assetBeneficiaries_beneficaryId_fkey" FOREIGN KEY (beneficary_id) REFERENCES beneficiaries(id) ON DELETE CASCADE not valid;

alter table "public"."asset_beneficiaries" validate constraint "public_assetBeneficiaries_beneficaryId_fkey";

alter table "public"."shareholders" add constraint "public_shareholders_businessId_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE not valid;

alter table "public"."shareholders" validate constraint "public_shareholders_businessId_fkey";

grant delete on table "public"."asset_beneficiaries" to "anon";

grant insert on table "public"."asset_beneficiaries" to "anon";

grant references on table "public"."asset_beneficiaries" to "anon";

grant select on table "public"."asset_beneficiaries" to "anon";

grant trigger on table "public"."asset_beneficiaries" to "anon";

grant truncate on table "public"."asset_beneficiaries" to "anon";

grant update on table "public"."asset_beneficiaries" to "anon";

grant delete on table "public"."asset_beneficiaries" to "authenticated";

grant insert on table "public"."asset_beneficiaries" to "authenticated";

grant references on table "public"."asset_beneficiaries" to "authenticated";

grant select on table "public"."asset_beneficiaries" to "authenticated";

grant trigger on table "public"."asset_beneficiaries" to "authenticated";

grant truncate on table "public"."asset_beneficiaries" to "authenticated";

grant update on table "public"."asset_beneficiaries" to "authenticated";

grant delete on table "public"."asset_beneficiaries" to "service_role";

grant insert on table "public"."asset_beneficiaries" to "service_role";

grant references on table "public"."asset_beneficiaries" to "service_role";

grant select on table "public"."asset_beneficiaries" to "service_role";

grant trigger on table "public"."asset_beneficiaries" to "service_role";

grant truncate on table "public"."asset_beneficiaries" to "service_role";

grant update on table "public"."asset_beneficiaries" to "service_role";

grant delete on table "public"."assets" to "anon";

grant insert on table "public"."assets" to "anon";

grant references on table "public"."assets" to "anon";

grant select on table "public"."assets" to "anon";

grant trigger on table "public"."assets" to "anon";

grant truncate on table "public"."assets" to "anon";

grant update on table "public"."assets" to "anon";

grant delete on table "public"."assets" to "authenticated";

grant insert on table "public"."assets" to "authenticated";

grant references on table "public"."assets" to "authenticated";

grant select on table "public"."assets" to "authenticated";

grant trigger on table "public"."assets" to "authenticated";

grant truncate on table "public"."assets" to "authenticated";

grant update on table "public"."assets" to "authenticated";

grant delete on table "public"."assets" to "service_role";

grant insert on table "public"."assets" to "service_role";

grant references on table "public"."assets" to "service_role";

grant select on table "public"."assets" to "service_role";

grant trigger on table "public"."assets" to "service_role";

grant truncate on table "public"."assets" to "service_role";

grant update on table "public"."assets" to "service_role";

grant delete on table "public"."beneficiaries" to "anon";

grant insert on table "public"."beneficiaries" to "anon";

grant references on table "public"."beneficiaries" to "anon";

grant select on table "public"."beneficiaries" to "anon";

grant trigger on table "public"."beneficiaries" to "anon";

grant truncate on table "public"."beneficiaries" to "anon";

grant update on table "public"."beneficiaries" to "anon";

grant delete on table "public"."beneficiaries" to "authenticated";

grant insert on table "public"."beneficiaries" to "authenticated";

grant references on table "public"."beneficiaries" to "authenticated";

grant select on table "public"."beneficiaries" to "authenticated";

grant trigger on table "public"."beneficiaries" to "authenticated";

grant truncate on table "public"."beneficiaries" to "authenticated";

grant update on table "public"."beneficiaries" to "authenticated";

grant delete on table "public"."beneficiaries" to "service_role";

grant insert on table "public"."beneficiaries" to "service_role";

grant references on table "public"."beneficiaries" to "service_role";

grant select on table "public"."beneficiaries" to "service_role";

grant trigger on table "public"."beneficiaries" to "service_role";

grant truncate on table "public"."beneficiaries" to "service_role";

grant update on table "public"."beneficiaries" to "service_role";

grant delete on table "public"."businesses" to "anon";

grant insert on table "public"."businesses" to "anon";

grant references on table "public"."businesses" to "anon";

grant select on table "public"."businesses" to "anon";

grant trigger on table "public"."businesses" to "anon";

grant truncate on table "public"."businesses" to "anon";

grant update on table "public"."businesses" to "anon";

grant delete on table "public"."businesses" to "authenticated";

grant insert on table "public"."businesses" to "authenticated";

grant references on table "public"."businesses" to "authenticated";

grant select on table "public"."businesses" to "authenticated";

grant trigger on table "public"."businesses" to "authenticated";

grant truncate on table "public"."businesses" to "authenticated";

grant update on table "public"."businesses" to "authenticated";

grant delete on table "public"."businesses" to "service_role";

grant insert on table "public"."businesses" to "service_role";

grant references on table "public"."businesses" to "service_role";

grant select on table "public"."businesses" to "service_role";

grant trigger on table "public"."businesses" to "service_role";

grant truncate on table "public"."businesses" to "service_role";

grant update on table "public"."businesses" to "service_role";

grant delete on table "public"."clients" to "anon";

grant insert on table "public"."clients" to "anon";

grant references on table "public"."clients" to "anon";

grant select on table "public"."clients" to "anon";

grant trigger on table "public"."clients" to "anon";

grant truncate on table "public"."clients" to "anon";

grant update on table "public"."clients" to "anon";

grant delete on table "public"."clients" to "authenticated";

grant insert on table "public"."clients" to "authenticated";

grant references on table "public"."clients" to "authenticated";

grant select on table "public"."clients" to "authenticated";

grant trigger on table "public"."clients" to "authenticated";

grant truncate on table "public"."clients" to "authenticated";

grant update on table "public"."clients" to "authenticated";

grant delete on table "public"."clients" to "service_role";

grant insert on table "public"."clients" to "service_role";

grant references on table "public"."clients" to "service_role";

grant select on table "public"."clients" to "service_role";

grant trigger on table "public"."clients" to "service_role";

grant truncate on table "public"."clients" to "service_role";

grant update on table "public"."clients" to "service_role";

grant delete on table "public"."debts" to "anon";

grant insert on table "public"."debts" to "anon";

grant references on table "public"."debts" to "anon";

grant select on table "public"."debts" to "anon";

grant trigger on table "public"."debts" to "anon";

grant truncate on table "public"."debts" to "anon";

grant update on table "public"."debts" to "anon";

grant delete on table "public"."debts" to "authenticated";

grant insert on table "public"."debts" to "authenticated";

grant references on table "public"."debts" to "authenticated";

grant select on table "public"."debts" to "authenticated";

grant trigger on table "public"."debts" to "authenticated";

grant truncate on table "public"."debts" to "authenticated";

grant update on table "public"."debts" to "authenticated";

grant delete on table "public"."debts" to "service_role";

grant insert on table "public"."debts" to "service_role";

grant references on table "public"."debts" to "service_role";

grant select on table "public"."debts" to "service_role";

grant trigger on table "public"."debts" to "service_role";

grant truncate on table "public"."debts" to "service_role";

grant update on table "public"."debts" to "service_role";

grant delete on table "public"."goals" to "anon";

grant insert on table "public"."goals" to "anon";

grant references on table "public"."goals" to "anon";

grant select on table "public"."goals" to "anon";

grant trigger on table "public"."goals" to "anon";

grant truncate on table "public"."goals" to "anon";

grant update on table "public"."goals" to "anon";

grant delete on table "public"."goals" to "authenticated";

grant insert on table "public"."goals" to "authenticated";

grant references on table "public"."goals" to "authenticated";

grant select on table "public"."goals" to "authenticated";

grant trigger on table "public"."goals" to "authenticated";

grant truncate on table "public"."goals" to "authenticated";

grant update on table "public"."goals" to "authenticated";

grant delete on table "public"."goals" to "service_role";

grant insert on table "public"."goals" to "service_role";

grant references on table "public"."goals" to "service_role";

grant select on table "public"."goals" to "service_role";

grant trigger on table "public"."goals" to "service_role";

grant truncate on table "public"."goals" to "service_role";

grant update on table "public"."goals" to "service_role";

grant delete on table "public"."shareholders" to "anon";

grant insert on table "public"."shareholders" to "anon";

grant references on table "public"."shareholders" to "anon";

grant select on table "public"."shareholders" to "anon";

grant trigger on table "public"."shareholders" to "anon";

grant truncate on table "public"."shareholders" to "anon";

grant update on table "public"."shareholders" to "anon";

grant delete on table "public"."shareholders" to "authenticated";

grant insert on table "public"."shareholders" to "authenticated";

grant references on table "public"."shareholders" to "authenticated";

grant select on table "public"."shareholders" to "authenticated";

grant trigger on table "public"."shareholders" to "authenticated";

grant truncate on table "public"."shareholders" to "authenticated";

grant update on table "public"."shareholders" to "authenticated";

grant delete on table "public"."shareholders" to "service_role";

grant insert on table "public"."shareholders" to "service_role";

grant references on table "public"."shareholders" to "service_role";

grant select on table "public"."shareholders" to "service_role";

grant trigger on table "public"."shareholders" to "service_role";

grant truncate on table "public"."shareholders" to "service_role";

grant update on table "public"."shareholders" to "service_role";


