create table "public"."businesses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "valuation" bigint not null,
    "ebitda" bigint not null,
    "appreciationRate" smallint not null,
    "term" smallint not null
);


alter table "public"."businesses" enable row level security;

create table "public"."shareholders" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "name" text not null,
    "sharePercentage" smallint not null,
    "insuranceCoverage" bigint not null,
    "ebitdaContributionPercentage" smallint not null,
    "businessId" bigint not null
);


alter table "public"."shareholders" enable row level security;

CREATE UNIQUE INDEX businesses_pkey ON public.businesses USING btree (id);

CREATE UNIQUE INDEX shareholders_pkey ON public.shareholders USING btree (id);

alter table "public"."businesses" add constraint "businesses_pkey" PRIMARY KEY using index "businesses_pkey";

alter table "public"."shareholders" add constraint "shareholders_pkey" PRIMARY KEY using index "shareholders_pkey";

alter table "public"."shareholders" add constraint "public_shareholders_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES businesses(id) ON DELETE CASCADE not valid;

alter table "public"."shareholders" validate constraint "public_shareholders_businessId_fkey";

grant delete on table "public"."businesses" to "anon";

grant insert on table "public"."businesses" to "anon";

grant references on table "public"."businesses" to "anon";

grant select on table "public"."businesses" to "anon";

grant trigger on table "public"."businesses" to "anon";

grant truncate on table "public"."businesses" to "anon";

grant update on table "public"."businesses" to "anon";

grant delete on table "public"."businesses" to "authenticated";

grant insert on table "public"."businesses" to "authenticated";

grant references on table "public"."businesses" to "authenticated";

grant select on table "public"."businesses" to "authenticated";

grant trigger on table "public"."businesses" to "authenticated";

grant truncate on table "public"."businesses" to "authenticated";

grant update on table "public"."businesses" to "authenticated";

grant delete on table "public"."businesses" to "service_role";

grant insert on table "public"."businesses" to "service_role";

grant references on table "public"."businesses" to "service_role";

grant select on table "public"."businesses" to "service_role";

grant trigger on table "public"."businesses" to "service_role";

grant truncate on table "public"."businesses" to "service_role";

grant update on table "public"."businesses" to "service_role";

grant delete on table "public"."shareholders" to "anon";

grant insert on table "public"."shareholders" to "anon";

grant references on table "public"."shareholders" to "anon";

grant select on table "public"."shareholders" to "anon";

grant trigger on table "public"."shareholders" to "anon";

grant truncate on table "public"."shareholders" to "anon";

grant update on table "public"."shareholders" to "anon";

grant delete on table "public"."shareholders" to "authenticated";

grant insert on table "public"."shareholders" to "authenticated";

grant references on table "public"."shareholders" to "authenticated";

grant select on table "public"."shareholders" to "authenticated";

grant trigger on table "public"."shareholders" to "authenticated";

grant truncate on table "public"."shareholders" to "authenticated";

grant update on table "public"."shareholders" to "authenticated";

grant delete on table "public"."shareholders" to "service_role";

grant insert on table "public"."shareholders" to "service_role";

grant references on table "public"."shareholders" to "service_role";

grant select on table "public"."shareholders" to "service_role";

grant trigger on table "public"."shareholders" to "service_role";

grant truncate on table "public"."shareholders" to "service_role";

grant update on table "public"."shareholders" to "service_role";


