create table "public"."debts" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "name" text not null,
    "initialValue" bigint not null,
    "yearAcquired" integer not null,
    "rate" smallint not null,
    "term" smallint not null,
    "annualPayment" bigint not null,
    "insurableFutureValueDollars" bigint not null
);


alter table "public"."debts" enable row level security;

alter table "public"."businesses" drop column "created_at";

alter table "public"."businesses" add column "createdAt" timestamp with time zone not null default now();

CREATE UNIQUE INDEX debts_pkey ON public.debts USING btree (id);

alter table "public"."debts" add constraint "debts_pkey" PRIMARY KEY using index "debts_pkey";

grant delete on table "public"."debts" to "anon";

grant insert on table "public"."debts" to "anon";

grant references on table "public"."debts" to "anon";

grant select on table "public"."debts" to "anon";

grant trigger on table "public"."debts" to "anon";

grant truncate on table "public"."debts" to "anon";

grant update on table "public"."debts" to "anon";

grant delete on table "public"."debts" to "authenticated";

grant insert on table "public"."debts" to "authenticated";

grant references on table "public"."debts" to "authenticated";

grant select on table "public"."debts" to "authenticated";

grant trigger on table "public"."debts" to "authenticated";

grant truncate on table "public"."debts" to "authenticated";

grant update on table "public"."debts" to "authenticated";

grant delete on table "public"."debts" to "service_role";

grant insert on table "public"."debts" to "service_role";

grant references on table "public"."debts" to "service_role";

grant select on table "public"."debts" to "service_role";

grant trigger on table "public"."debts" to "service_role";

grant truncate on table "public"."debts" to "service_role";

grant update on table "public"."debts" to "service_role";


