create type "public"."assetTypes" as enum ('Cash', 'Stocks', 'Bonds', 'Real Estate', 'Mutual Funds', 'Retirement Account', 'Crypto', 'Life Insurance');

create type "public"."provinces" as enum ('AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'NT', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT');

create table "public"."assetBeneficiaries" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "allocation" smallint not null,
    "assetId" bigint not null,
    "beneficaryId" bigint not null
);


alter table "public"."assetBeneficiaries" enable row level security;

create table "public"."assets" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "name" text not null,
    "initialValue" numeric not null,
    "currentValue" numeric not null,
    "yearAcquired" integer not null,
    "rate" smallint not null,
    "term" smallint not null,
    "type" "assetTypes" not null,
    "taxable" boolean not null,
    "liquid" boolean not null,
    "toBeSold" boolean not null
);


alter table "public"."assets" enable row level security;

create table "public"."beneficiaries" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "name" text not null,
    "allocation" smallint not null
);


alter table "public"."beneficiaries" enable row level security;

create table "public"."businesses" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "valuation" numeric not null,
    "ebitda" numeric not null,
    "appreciationRate" smallint not null,
    "term" smallint not null,
    "createdAt" timestamp with time zone not null default now()
);


alter table "public"."businesses" enable row level security;

create table "public"."clients" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "name" text not null,
    "birthDate" date not null,
    "expectedRetirementAge" smallint not null,
    "province" provinces not null,
    "annualIncome" numeric not null,
    "incomeMultiplier" smallint not null
);


alter table "public"."clients" enable row level security;

create table "public"."debts" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "name" text not null,
    "initialValue" numeric not null,
    "yearAcquired" integer not null,
    "rate" smallint not null,
    "term" smallint not null,
    "annualPayment" numeric not null,
    "insurableFutureValueDollars" numeric not null
);


alter table "public"."debts" enable row level security;

create table "public"."goals" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "name" text not null,
    "amount" numeric not null,
    "philanthropic" boolean not null
);


alter table "public"."goals" enable row level security;

create table "public"."shareholders" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "name" text not null,
    "sharePercentage" smallint not null,
    "insuranceCoverage" numeric not null,
    "ebitdaContributionPercentage" smallint not null,
    "businessId" bigint not null
);


alter table "public"."shareholders" enable row level security;

CREATE UNIQUE INDEX "assetBeneficiaries_pkey" ON public."assetBeneficiaries" USING btree (id);

CREATE UNIQUE INDEX assets_pkey ON public.assets USING btree (id);

CREATE UNIQUE INDEX beneficiaries_pkey ON public.beneficiaries USING btree (id);

CREATE UNIQUE INDEX businesses_pkey ON public.businesses USING btree (id);

CREATE UNIQUE INDEX client_pkey ON public.clients USING btree (id);

CREATE UNIQUE INDEX debts_pkey ON public.debts USING btree (id);

CREATE UNIQUE INDEX goals_pkey ON public.goals USING btree (id);

CREATE UNIQUE INDEX shareholders_pkey ON public.shareholders USING btree (id);

alter table "public"."assetBeneficiaries" add constraint "assetBeneficiaries_pkey" PRIMARY KEY using index "assetBeneficiaries_pkey";

alter table "public"."assets" add constraint "assets_pkey" PRIMARY KEY using index "assets_pkey";

alter table "public"."beneficiaries" add constraint "beneficiaries_pkey" PRIMARY KEY using index "beneficiaries_pkey";

alter table "public"."businesses" add constraint "businesses_pkey" PRIMARY KEY using index "businesses_pkey";

alter table "public"."clients" add constraint "client_pkey" PRIMARY KEY using index "client_pkey";

alter table "public"."debts" add constraint "debts_pkey" PRIMARY KEY using index "debts_pkey";

alter table "public"."goals" add constraint "goals_pkey" PRIMARY KEY using index "goals_pkey";

alter table "public"."shareholders" add constraint "shareholders_pkey" PRIMARY KEY using index "shareholders_pkey";

alter table "public"."assetBeneficiaries" add constraint "public_assetBeneficiaries_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES assets(id) ON DELETE CASCADE not valid;

alter table "public"."assetBeneficiaries" validate constraint "public_assetBeneficiaries_assetId_fkey";

alter table "public"."assetBeneficiaries" add constraint "public_assetBeneficiaries_beneficaryId_fkey" FOREIGN KEY ("beneficaryId") REFERENCES beneficiaries(id) ON DELETE CASCADE not valid;

alter table "public"."assetBeneficiaries" validate constraint "public_assetBeneficiaries_beneficaryId_fkey";

alter table "public"."shareholders" add constraint "public_shareholders_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES businesses(id) ON DELETE CASCADE not valid;

alter table "public"."shareholders" validate constraint "public_shareholders_businessId_fkey";

grant delete on table "public"."assetBeneficiaries" to "anon";

grant insert on table "public"."assetBeneficiaries" to "anon";

grant references on table "public"."assetBeneficiaries" to "anon";

grant select on table "public"."assetBeneficiaries" to "anon";

grant trigger on table "public"."assetBeneficiaries" to "anon";

grant truncate on table "public"."assetBeneficiaries" to "anon";

grant update on table "public"."assetBeneficiaries" to "anon";

grant delete on table "public"."assetBeneficiaries" to "authenticated";

grant insert on table "public"."assetBeneficiaries" to "authenticated";

grant references on table "public"."assetBeneficiaries" to "authenticated";

grant select on table "public"."assetBeneficiaries" to "authenticated";

grant trigger on table "public"."assetBeneficiaries" to "authenticated";

grant truncate on table "public"."assetBeneficiaries" to "authenticated";

grant update on table "public"."assetBeneficiaries" to "authenticated";

grant delete on table "public"."assetBeneficiaries" to "service_role";

grant insert on table "public"."assetBeneficiaries" to "service_role";

grant references on table "public"."assetBeneficiaries" to "service_role";

grant select on table "public"."assetBeneficiaries" to "service_role";

grant trigger on table "public"."assetBeneficiaries" to "service_role";

grant truncate on table "public"."assetBeneficiaries" to "service_role";

grant update on table "public"."assetBeneficiaries" to "service_role";

grant delete on table "public"."assets" to "anon";

grant insert on table "public"."assets" to "anon";

grant references on table "public"."assets" to "anon";

grant select on table "public"."assets" to "anon";

grant trigger on table "public"."assets" to "anon";

grant truncate on table "public"."assets" to "anon";

grant update on table "public"."assets" to "anon";

grant delete on table "public"."assets" to "authenticated";

grant insert on table "public"."assets" to "authenticated";

grant references on table "public"."assets" to "authenticated";

grant select on table "public"."assets" to "authenticated";

grant trigger on table "public"."assets" to "authenticated";

grant truncate on table "public"."assets" to "authenticated";

grant update on table "public"."assets" to "authenticated";

grant delete on table "public"."assets" to "service_role";

grant insert on table "public"."assets" to "service_role";

grant references on table "public"."assets" to "service_role";

grant select on table "public"."assets" to "service_role";

grant trigger on table "public"."assets" to "service_role";

grant truncate on table "public"."assets" to "service_role";

grant update on table "public"."assets" to "service_role";

grant delete on table "public"."beneficiaries" to "anon";

grant insert on table "public"."beneficiaries" to "anon";

grant references on table "public"."beneficiaries" to "anon";

grant select on table "public"."beneficiaries" to "anon";

grant trigger on table "public"."beneficiaries" to "anon";

grant truncate on table "public"."beneficiaries" to "anon";

grant update on table "public"."beneficiaries" to "anon";

grant delete on table "public"."beneficiaries" to "authenticated";

grant insert on table "public"."beneficiaries" to "authenticated";

grant references on table "public"."beneficiaries" to "authenticated";

grant select on table "public"."beneficiaries" to "authenticated";

grant trigger on table "public"."beneficiaries" to "authenticated";

grant truncate on table "public"."beneficiaries" to "authenticated";

grant update on table "public"."beneficiaries" to "authenticated";

grant delete on table "public"."beneficiaries" to "service_role";

grant insert on table "public"."beneficiaries" to "service_role";

grant references on table "public"."beneficiaries" to "service_role";

grant select on table "public"."beneficiaries" to "service_role";

grant trigger on table "public"."beneficiaries" to "service_role";

grant truncate on table "public"."beneficiaries" to "service_role";

grant update on table "public"."beneficiaries" to "service_role";

grant delete on table "public"."businesses" to "anon";

grant insert on table "public"."businesses" to "anon";

grant references on table "public"."businesses" to "anon";

grant select on table "public"."businesses" to "anon";

grant trigger on table "public"."businesses" to "anon";

grant truncate on table "public"."businesses" to "anon";

grant update on table "public"."businesses" to "anon";

grant delete on table "public"."businesses" to "authenticated";

grant insert on table "public"."businesses" to "authenticated";

grant references on table "public"."businesses" to "authenticated";

grant select on table "public"."businesses" to "authenticated";

grant trigger on table "public"."businesses" to "authenticated";

grant truncate on table "public"."businesses" to "authenticated";

grant update on table "public"."businesses" to "authenticated";

grant delete on table "public"."businesses" to "service_role";

grant insert on table "public"."businesses" to "service_role";

grant references on table "public"."businesses" to "service_role";

grant select on table "public"."businesses" to "service_role";

grant trigger on table "public"."businesses" to "service_role";

grant truncate on table "public"."businesses" to "service_role";

grant update on table "public"."businesses" to "service_role";

grant delete on table "public"."clients" to "anon";

grant insert on table "public"."clients" to "anon";

grant references on table "public"."clients" to "anon";

grant select on table "public"."clients" to "anon";

grant trigger on table "public"."clients" to "anon";

grant truncate on table "public"."clients" to "anon";

grant update on table "public"."clients" to "anon";

grant delete on table "public"."clients" to "authenticated";

grant insert on table "public"."clients" to "authenticated";

grant references on table "public"."clients" to "authenticated";

grant select on table "public"."clients" to "authenticated";

grant trigger on table "public"."clients" to "authenticated";

grant truncate on table "public"."clients" to "authenticated";

grant update on table "public"."clients" to "authenticated";

grant delete on table "public"."clients" to "service_role";

grant insert on table "public"."clients" to "service_role";

grant references on table "public"."clients" to "service_role";

grant select on table "public"."clients" to "service_role";

grant trigger on table "public"."clients" to "service_role";

grant truncate on table "public"."clients" to "service_role";

grant update on table "public"."clients" to "service_role";

grant delete on table "public"."debts" to "anon";

grant insert on table "public"."debts" to "anon";

grant references on table "public"."debts" to "anon";

grant select on table "public"."debts" to "anon";

grant trigger on table "public"."debts" to "anon";

grant truncate on table "public"."debts" to "anon";

grant update on table "public"."debts" to "anon";

grant delete on table "public"."debts" to "authenticated";

grant insert on table "public"."debts" to "authenticated";

grant references on table "public"."debts" to "authenticated";

grant select on table "public"."debts" to "authenticated";

grant trigger on table "public"."debts" to "authenticated";

grant truncate on table "public"."debts" to "authenticated";

grant update on table "public"."debts" to "authenticated";

grant delete on table "public"."debts" to "service_role";

grant insert on table "public"."debts" to "service_role";

grant references on table "public"."debts" to "service_role";

grant select on table "public"."debts" to "service_role";

grant trigger on table "public"."debts" to "service_role";

grant truncate on table "public"."debts" to "service_role";

grant update on table "public"."debts" to "service_role";

grant delete on table "public"."goals" to "anon";

grant insert on table "public"."goals" to "anon";

grant references on table "public"."goals" to "anon";

grant select on table "public"."goals" to "anon";

grant trigger on table "public"."goals" to "anon";

grant truncate on table "public"."goals" to "anon";

grant update on table "public"."goals" to "anon";

grant delete on table "public"."goals" to "authenticated";

grant insert on table "public"."goals" to "authenticated";

grant references on table "public"."goals" to "authenticated";

grant select on table "public"."goals" to "authenticated";

grant trigger on table "public"."goals" to "authenticated";

grant truncate on table "public"."goals" to "authenticated";

grant update on table "public"."goals" to "authenticated";

grant delete on table "public"."goals" to "service_role";

grant insert on table "public"."goals" to "service_role";

grant references on table "public"."goals" to "service_role";

grant select on table "public"."goals" to "service_role";

grant trigger on table "public"."goals" to "service_role";

grant truncate on table "public"."goals" to "service_role";

grant update on table "public"."goals" to "service_role";

grant delete on table "public"."shareholders" to "anon";

grant insert on table "public"."shareholders" to "anon";

grant references on table "public"."shareholders" to "anon";

grant select on table "public"."shareholders" to "anon";

grant trigger on table "public"."shareholders" to "anon";

grant truncate on table "public"."shareholders" to "anon";

grant update on table "public"."shareholders" to "anon";

grant delete on table "public"."shareholders" to "authenticated";

grant insert on table "public"."shareholders" to "authenticated";

grant references on table "public"."shareholders" to "authenticated";

grant select on table "public"."shareholders" to "authenticated";

grant trigger on table "public"."shareholders" to "authenticated";

grant truncate on table "public"."shareholders" to "authenticated";

grant update on table "public"."shareholders" to "authenticated";

grant delete on table "public"."shareholders" to "service_role";

grant insert on table "public"."shareholders" to "service_role";

grant references on table "public"."shareholders" to "service_role";

grant select on table "public"."shareholders" to "service_role";

grant trigger on table "public"."shareholders" to "service_role";

grant truncate on table "public"."shareholders" to "service_role";

grant update on table "public"."shareholders" to "service_role";


